# Generated by Django 5.0.4 on 2024-04-15 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetodoacao',
            name='voluntarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='voluntarios.uservoluntario'),
        ),
    ]
