# Generated by Django 5.0.4 on 2024-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0002_alter_projetodoacao_voluntarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projetodoacao',
            name='voluntarios',
        ),
        migrations.AddField(
            model_name='projetodoacao',
            name='voluntarios',
            field=models.ManyToManyField(blank=True, null=True, to='voluntarios.uservoluntario'),
        ),
    ]
