# Generated by Django 5.0.4 on 2024-04-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_remove_projetodoacao_voluntarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetodoacao',
            name='voluntarios',
            field=models.ManyToManyField(to='voluntarios.uservoluntario'),
        ),
    ]
